var dict = {
  "Flags/afganistan.svg":"Afganistan",
  "Flags/aland.svg":"Åland",
  "Flags/albania.svg":"Albania",
  "Flags/alemania.svg":"Alemania",
  "Flags/algeria.svg":"Algeria",
  "Flags/andorra.svg":"Andorra",
  "Flags/angola.svg":"Angola",
  "Flags/anguila.svg":"Anguila",
  "Flags/arabia saudita.svg":"Arabia Saudita",
  "Flags/argentina.svg":"Argentina",
  "Flags/armenia.svg":"Armenia",
  "Flags/aruba.svg":"Aruba",
  "Flags/australia.svg":"Australia",
  "Flags/austria.svg":"Austria",
  "Flags/azerbaiyan.svg":"Azerbaiyan",
  "Flags/bahamas.svg":"Bahamas",
  "Flags/banglades.svg":"Banglades",
  "Flags/barbados.svg":"Barbados",
  "Flags/barein.svg":"Barein",
  "Flags/belice.svg":"Belice",
  "Flags/benin.svg":"Benin",
  "Flags/bermudas.svg":"Bermudas",
  "Flags/bielorusia.svg":"Bielorusia",
  "Flags/bolivia.svg":"Bolivia",
  "Flags/bonaire.svg":"Bonaire",
  "Flags/bosnia y herzegovina.svg":"Bosnia y Herzegovina",
  "Flags/botswana.svg":"Botswana",
  "Flags/brazil.svg":"Brazil",
  "Flags/brunei.svg":"Brunei",
  "Flags/bulgaria.svg":"Bulgaria",
  "Flags/burundi.svg":"Burundi",
  "Flags/butan.svg":"Butan",
  "Flags/cabo verde.svg":"Cabo Verde",
  "Flags/camboya.svg":"Camboya",
  "Flags/camerun.svg":"Camerun",
  "Flags/canada.svg":"Canada",
  "Flags/catar.svg":"Catar",
  "Flags/chad.svg":"Chad",
  "Flags/chile.svg":"Chile",
  "Flags/chipre.svg":"Chipre",
  "Flags/china.svg":"China",
  "Flags/ciudad del vaticano.svg":"Ciudad del Vaticano",
  "Flags/colombia.svg":"Colombia",
  "Flags/comoras.svg":"Comoras",
  "Flags/corea del norte.svg":"Corea del Norte",
  "Flags/corea del sur.svg":"Corea del Sur",
  "Flags/costa de marfil.svg":"Costa de Marfil",
  "Flags/costa rica.svg":"Costa Rica",
  "Flags/croacia.svg":"Croacia",
  "Flags/cuba.svg":"Cuba",
  "Flags/curazao.svg":"Curazao",
  "Flags/dinamarca.svg":"Dinamarca",
  "Flags/dominica.svg":"Dominica",
  "Flags/ecuador.svg":"Ecuador",
  "Flags/egipto.svg":"Egipto",
  "Flags/el salvador.svg":"El Salvador",
  "Flags/emiratos arabes unidos.svg":"Emiratos Arabes Unidos",
  "Flags/eritrea.svg":"Eritrea",
  "Flags/escocia.svg":"Escocia",
  "Flags/eslovaquia.svg":"Eslovaquia",
  "Flags/eslovenia.svg":"Eslovenia",
  "Flags/estados federados de micronesia.svg":"Estados Federados de Micronesia",
  "Flags/estados unidos.svg":"Estados Unidos",
  "Flags/estonia.svg":"Estonia",
  "Flags/etiopia.svg":"Etiopia",
  "Flags/filipinas.svg":"Filipinas",
  "Flags/finlandia.svg":"Finlandia",
  "Flags/fiyi.svg":"Fiyi",
  "Flags/francia.svg":"Francia",
  "Flags/gabon.svg":"Gabon",
  "Flags/gales.svg":"Gales",
  "Flags/gambia.svg":"Gambia",
  "Flags/georgia.svg":"Georgia",
  "Flags/ghana.svg":"Ghana",
  "Flags/gibraltar.svg":"Gibraltar",
  "Flags/granada.svg":"Granada",
  "Flags/grecia.svg":"Grecia",
  "Flags/groenlandia.svg":"Groenlandia",
  "Flags/guam.svg":"Guam",
  "Flags/guatemala.svg":"Guatemala",
  "Flags/guayana francesa.svg":"Guayana Francesa",
  "Flags/guernsey.svg":"Guernsey",
  "Flags/guinea bisau.svg":"Guinea Bisau",
  "Flags/guinea equatorial.svg":"Guinea Equatorial",
  "Flags/guinea.svg":"Guinea",
  "Flags/guadalupe.svg":"Guadalupe",
  "Flags/guyana.svg":"Guyana",
  "Flags/haiti.svg":"Haiti",
  "Flags/hawaii.svg":"Hawaii",
  "Flags/honduras.svg":"Honduras",
  "Flags/hong kong.svg":"Hong Kong",
  "Flags/hungria.svg":"Hungria",
  "Flags/india.svg":"India",
  "Flags/indonesia.svg":"Indonesia",
  "Flags/inglaterra.svg":"Inglaterra",
  "Flags/irak.svg":"Irak",
  "Flags/iran.svg":"Iran",
  "Flags/irlanda del norte.svg":"Irlanda del Norte",
  "Flags/irlanda.svg":"Irlanda",
  "Flags/isla de man.svg":"Isla de Man",
  "Flags/isla de navidad.svg":"Isla de Navidad",
  "Flags/islandia.svg":"Islandia",
  "Flags/islas caiman.svg":"Islas Caiman",
  "Flags/islas canarias.svg":"Islas Canarias",
  "Flags/islas cocos.svg":"Islas Cocos",
  "Flags/islas cook.svg":"Islas Cook",
  "Flags/islas feroe.svg":"Islas Feroe",
  "Flags/islas georgias del sur y sandwich del sur.svg":"Islas Georgias del Sur y Sandwich del Sur",
  "Flags/islas malvinas.svg":"Islas Malvinas",
  "Flags/islas marianas del norte.svg":"Islas Marianas del Norte",
  "Flags/islas marshall.svg":"Islas Marshall",
  "Flags/islas norfolk.svg":"Islas Norfolk",
  "Flags/islas pitcairn.svg":"Islas Pircairn",
  "Flags/islas salomon.svg":"Islas Salomon",
  "Flags/isla santa elena.svg":"Isla Santa Elena",
  "Flags/islas turcas y caicos.svg":"Islas Turcas y Caicos",
  "Flags/islas virgenes britanicas.svg":"Islas Virgenes Britanicas",
  "Flags/islas virgenes de los estados unidos.svg":"Islas Virgenes de los Estados Unidos",
  "Flags/israel.svg":"Israel",
  "Flags/italia.svg":"Italia",
  "Flags/jordania.svg":"Jordania",
  "Flags/jamaica.svg":"Jamaica",
  "Flags/jersey.svg":"Jersey",
  "Flags/kazajistan.svg":"Kasajistan",
  "Flags/kenia.svg":"Kenia",
  "Flags/kirguistan.svg":"Kirguistan",
  "Flags/kiribati.svg":"Kiribati",
  "Flags/kosovo.svg":"Kosovo",
  "Flags/kuwait.svg":"Kuwait",
  "Flags/laos.svg":"Laos",
  "Flags/lesoto.svg":"Lesoto",
  "Flags/letonia.svg":"Letonia",
  "Flags/libano.svg":"Libano",
  "Flags/liberia.svg":"Liberia",
  "Flags/libia.svg":"Libia",
  "Flags/liechteinstein.svg":"Liechteinstein",
  "Flags/lituania.svg":"Lituania",
  "Flags/luxemburgo.svg":"Luxemburgo",
  "Flags/macao.svg":"Macao",
  "Flags/macedonia del norte.svg":"Macedonia del Norte",
  "Flags/madagascar.svg":"Madagascar",
  "Flags/malasia.svg":"Malasia",
  "Flags/malawi.svg":"Malawi",
  "Flags/maldivas.svg":"Maldivas",
  "Flags/mali.svg":"Mali",
  "Flags/malta.svg":"Malta",
  "Flags/marruecos.svg":"Marruecos",
  "Flags/mauricio.svg":"Mauricio",
  "Flags/mauritania.svg":"Mauritania",
  "Flags/martinica.svg":"Martinica",
  "Flags/mayotte.svg":"Mayotte",
  "Flags/mexico.svg":"Mexico",
  "Flags/moldavia.svg":"Moldavia",
  "Flags/monaco.svg":"Monaco",
  "Flags/mongolia.svg":"Mongolia",
  "Flags/montenegro.svg":"Montenegro",
  "Flags/montserrat.svg":"Montserrat",
  "Flags/mozambique.svg":"Mozambique",
  "Flags/myanmar.svg":"Myanmar",
  "Flags/namibia.svg":"Namibia",
  "Flags/nauru.svg":"Nauru",
  "Flags/nepal.svg":"Nepal",
  "Flags/nicaragua.svg":"Nicaragua",
  "Flags/niger.svg":"Niger",
  "Flags/nigeria.svg":"Nigeria",
  "Flags/niue.svg":"Niue",
  "Flags/noruega.svg":"Noruega",
  "Flags/nueva caledonia.svg":"Nueva Caledonia",
  "Flags/nueva zelanda.svg":"Nueva Zelanda",
  "Flags/oman.svg":"Oman",
  "Flags/paises bajos.svg":"Paises Bajos",
  "Flags/pakistan.svg":"Pakistan",
  "Flags/palaos.svg":"Palaos",
  "Flags/palestina.svg":"Palestina",
  "Flags/papua nueva guinea.svg":"Papua Nueva Guinea",
  "Flags/paraguay.svg":"Paraguay",
  "Flags/peru.svg":"Peru",
  "Flags/polinesia francesa.svg":"Polinesia Francesa",
  "Flags/polonia.svg":"Polonia",
  "Flags/portugal.svg":"Portugal",
  "Flags/puerto rico.svg":"Puerto Rico",
  "Flags/reino unido.svg":"Reino Unido",
  "Flags/republica centroafricana.svg":"Republica Centroafricana",
  "Flags/republica checa.svg":"Republica Checa",
  "Flags/republica del congo.svg":"Republica del Congo",
  "Flags/republica democratica del congo.svg":"Republica Democratica del Congo",
  "Flags/republica dominicana.svg":"Republica Dominicana",
  "Flags/reunion.svg":"Reunion",
  "Flags/ruanda.svg":"Ruanda",
  "Flags/rumania.svg":"Rumania",
  "Flags/rusia.svg":"Rusia",
  "Flags/saba.svg":"Saba",
  "Flags/samoa americana.svg":"Samoa Americana",
  "Flags/samoa.svg":"Samoa",
  "Flags/san bartolome.svg":"San Bartolome",
  "Flags/san cristobal y nieves.svg":"San Cristobal y Nieves",
  "Flags/san eustaquio.svg":"San Eustaquio",
  "Flags/san marino.svg":"San Marino",
  "Flags/san martin (francia).svg":"San Martin (Francia)",
  "Flags/san pedro y miquelon.svg":"San Pedro y Miquelon",
  "Flags/san vincente y las granadinas.svg":"San Vincente y las Granadinas",
  "Flags/santa lucia.svg":"Santa Lucia",
  "Flags/santo tome y principe.svg":"Santo Tome y Principe",
  "Flags/senegal.svg":"Senegal",
  "Flags/serbia.svg":"Serbia",
  "Flags/seychelles.svg":"Seychelles",
  "Flags/sierra leona.svg":"Sierra Leona",
  "Flags/singapur.svg":"Singapur",
  "Flags/sint marteen.svg":"Sint Marteen",
  "Flags/siria.svg":"Siria",
  "Flags/somalia.svg":"Somalia",
  "Flags/sri lanka.svg":"Sri Lanka",
  "Flags/suazilandia.svg":"Suazilandia",
  "Flags/suiza.svg":"Suiza",
  "Flags/sudan del sur.svg":"Sudan del Sur",
  "Flags/sudan.svg":"Sudan",
  "Flags/sudafrica.svg":"Sudafrica",
  "Flags/suecia.svg":"Suecia",
  "Flags/surinam.svg":"Surinam",
  "Flags/taiwan.svg":"Taiwan",
  "Flags/tanzania.svg":"Tanzania",
  "Flags/tayikistan.svg":"Tayikistan",
  "Flags/territorio britanico del oceano indico.svg":"Territorio Britanico del Oceano Indico",
  "Flags/tierras australes y antarticas francesas.svg":"Tierras Australes y Antarticas Francesas",
  "Flags/timor oriental.svg":"Timor Oriental",
  "Flags/tokelau.svg":"Tokelau",
  "Flags/tonga.svg":"Tonga",
  "Flags/trinidad y tobago.svg":"Trinidad y Tobago",
  "Flags/tunez.svg":"Tunez",
  "Flags/turkmenistan.svg":"Turkmenistan",
  "Flags/tuvalu.svg":"Tuvalu",
  "Flags/ucrania.svg":"Ucrania",
  "Flags/uganda.svg":"Uganda",
  "Flags/uruguay.svg":"Uruguay",
  "Flags/uzbekistan.svg":"Uzbekistan",
  "Flags/vanuatu.svg":"Vanuatu",
  "Flags/venezuela.svg":"Venezuela",
  "Flags/vietnam.svg":"Vietnam",
  "Flags/wallis y futuna.svg":"Wallis y Futuna",
  "Flags/yibuti.svg":"Yibuti",
  "Flags/zambia.svg":"Zambia",
  "Flags/zimbabue.svg":"Zimbabue"
}
